services:
  banking-api:
    build:
      context: .
    ports:
      - "5000:5000"
    container_name: banking_api
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s