services:
  banking-api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.main
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
    container_name: banking_api
    command: ["python", "-m", "flask", "run", "--host=0.0.0.0", "--port=5000"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s