name: CI Test Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Build Docker image
      run: docker build -t banking-api .

    - name: Start Docker container
      run: docker run -d -p 5000:5000 --name banking_api banking-api

    - name: Wait for container to be healthy
      run: |
        for i in {1..10}; do
          if curl --fail http://localhost:5000/health; then
            echo "API is healthy!"
            break
          fi
          echo "Waiting for API to be healthy..."
          sleep 5
        done

    - name: Install test dependencies
      run: |
        pip install pytest requests

    - name: Run Tests
      run: |
        pytest tests/test_banking_api.py --maxfail=1 --disable-warnings --tb=short

    - name: Cleanup
      if: always()
      run: docker rm -f banking_api || true
