name: CI Test Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest requests

    - name: Start Flask app in background
      run: |
        nohup python app.py > flask.log 2>&1 &
        sleep 5

    - name: Run Tests
      run: |
        pytest tests/test_banking_api.py --maxfail=1 --disable-warnings --tb=short
